name = "hotsnack-gallery"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "hotsnack-gallery-db"
database_id = "placeholder-id"
