name = "hotsnack-gallery"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "hotsnack-gallery-db"
database_id = "b57a4495-b438-45fa-9d9a-d8068f42dd4a"
